# Generated by Django 2.0.1 on 2018-01-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namer', '0002_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
