# Generated by Django 2.0.1 on 2018-01-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namer', '0003_auto_20180125_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
