# Generated by Django 2.0.1 on 2018-01-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namer', '0004_auto_20180125_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
        migrations.AddField(
            model_name='image',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
