# Generated by Django 2.0.1 on 2018-01-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namer', '0007_auto_20180126_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='solved',
            field=models.IntegerField(blank=True),
        ),
    ]
