# Generated by Django 2.0.1 on 2018-01-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namer', '0009_auto_20180126_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='solved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
